- ros_topic_name: "/yolo/rgb"
  gz_topic_name: "/yolo/rgb"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: "/yolo/bbox"
  gz_topic_name: "/yolo/bbox"
  ros_type_name: "vision_msgs/msg/Detection2DArray"
  gz_type_name: "gz.msgs.AnnotatedAxisAligned2DBox_V"
  direction: GZ_TO_ROS
  qos_profile: SENSOR_DATA

- ros_topic_name: "/yolo/capture/trigger"
  gz_topic_name: "/yolo/capture/trigger"
  ros_type_name: "std_msgs/msg/Bool"
  gz_type_name: "gz.msgs.Boolean"
  direction: ROS_TO_GZ
